# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.cache/wt [current_project]
set_property parent.project_path C:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/Fysek/Documents/projects/cordic/ip_repo [current_project]
set_property ip_output_repo c:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/hdl/cordic_synth_block_wrapper.v
add_files C:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/cordic_synth_block.bd
set_property used_in_implementation false [get_files -all c:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/ip/cordic_synth_block_processing_system7_0_0/cordic_synth_block_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/ip/cordic_synth_block_rst_ps7_0_100M_0/cordic_synth_block_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/ip/cordic_synth_block_rst_ps7_0_100M_0/cordic_synth_block_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/ip/cordic_synth_block_rst_ps7_0_100M_0/cordic_synth_block_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/ip/cordic_synth_block_auto_pc_0/cordic_synth_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/cordic_synth_block_ooc.xdc]
set_property is_locked true [get_files C:/Users/Fysek/Documents/projects/cordic/cordic_project/cordic_project.srcs/sources_1/bd/cordic_synth_block/cordic_synth_block.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top cordic_synth_block_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef cordic_synth_block_wrapper.dcp

catch { report_utilization -file cordic_synth_block_wrapper_utilization_synth.rpt -pb cordic_synth_block_wrapper_utilization_synth.pb }
