# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cordic_synth_block/cordic_synth_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_block || ORIG_REF_NAME==cordic_synth_block}]

# IP: bd/cordic_synth_block/ip/cordic_synth_block_processing_system7_0_0/cordic_synth_block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_block_processing_system7_0_0 || ORIG_REF_NAME==cordic_synth_block_processing_system7_0_0}]

# IP: bd/cordic_synth_block/ip/cordic_synth_block_cordic_project_ip_synth_0_0/cordic_synth_block_cordic_project_ip_synth_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_block_cordic_project_ip_synth_0_0 || ORIG_REF_NAME==cordic_synth_block_cordic_project_ip_synth_0_0}]

# IP: bd/cordic_synth_block/ip/cordic_synth_block_ps7_0_axi_periph_0/cordic_synth_block_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==cordic_synth_block_ps7_0_axi_periph_0}]

# IP: bd/cordic_synth_block/ip/cordic_synth_block_rst_ps7_0_100M_0/cordic_synth_block_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_block_rst_ps7_0_100M_0 || ORIG_REF_NAME==cordic_synth_block_rst_ps7_0_100M_0}]

# IP: bd/cordic_synth_block/ip/cordic_synth_block_auto_pc_0/cordic_synth_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_block_auto_pc_0 || ORIG_REF_NAME==cordic_synth_block_auto_pc_0}]

# XDC: bd/cordic_synth_block/cordic_synth_block_ooc.xdc
