# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cordic_synth_design/cordic_synth_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_design || ORIG_REF_NAME==cordic_synth_design}]

# IP: bd/cordic_synth_design/ip/cordic_synth_design_cordic_synth_ip_0_0/cordic_synth_design_cordic_synth_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_design_cordic_synth_ip_0_0 || ORIG_REF_NAME==cordic_synth_design_cordic_synth_ip_0_0}]

# IP: bd/cordic_synth_design/ip/cordic_synth_design_processing_system7_0_0/cordic_synth_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_design_processing_system7_0_0 || ORIG_REF_NAME==cordic_synth_design_processing_system7_0_0}]

# IP: bd/cordic_synth_design/ip/cordic_synth_design_ps7_0_axi_periph_0/cordic_synth_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==cordic_synth_design_ps7_0_axi_periph_0}]

# IP: bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==cordic_synth_design_rst_ps7_0_100M_0}]

# IP: bd/cordic_synth_design/ip/cordic_synth_design_auto_pc_0/cordic_synth_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_synth_design_auto_pc_0 || ORIG_REF_NAME==cordic_synth_design_auto_pc_0}]

# XDC: bd/cordic_synth_design/cordic_synth_design_ooc.xdc
