# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Fysek/Documents/projects/cordic/cordic_synth/cordic_synth.srcs/sources_1/bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0.xci
# IP: The module: 'cordic_synth_design_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fysek/Documents/projects/cordic/cordic_synth/cordic_synth.srcs/sources_1/bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_synth_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Fysek/Documents/projects/cordic/cordic_synth/cordic_synth.srcs/sources_1/bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_synth_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Fysek/Documents/projects/cordic/cordic_synth/cordic_synth.srcs/sources_1/bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_synth_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Fysek/Documents/projects/cordic/cordic_synth/cordic_synth.srcs/sources_1/bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0.xci
# IP: The module: 'cordic_synth_design_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fysek/Documents/projects/cordic/cordic_synth/cordic_synth.srcs/sources_1/bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_synth_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Fysek/Documents/projects/cordic/cordic_synth/cordic_synth.srcs/sources_1/bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_synth_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Fysek/Documents/projects/cordic/cordic_synth/cordic_synth.srcs/sources_1/bd/cordic_synth_design/ip/cordic_synth_design_rst_ps7_0_100M_0/cordic_synth_design_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic_synth_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
